review:
  uiRereviewTeam: aireview
  requestUiRereviewTeamOnOpen: true

mention:
  enabled: true

write:
  enabled: true
  allowPaths:
    - docs/**
  denyPaths:
    - .github/**
  secretScan:
    enabled: true
